<?php

$messages = array();
$messages['lastlogin'] = 'Poslední otevřená relace byla $date z IP adresy $from $geo.';
$messages['noinfo']    = 'Nejsou k dispozici žádné informace.';
$messages['timeout']   = 'Zobrazit informaci o poslední relaci';

$labels = array();
$labels['section_title'] = 'Poslední přihlášení';
$labels['info'] = 'Informace';
$labels['conf'] = 'Nastavení';
$labels['fornseconds'] = '$n sekund';
$labels['recentactivity'] = 'Poslední aktivita:';
$labels['ip'] = 'IP addresa';
$labels['hostname'] = 'Jméno hostitele';
$labels['timestamp'] = 'Datum/Čas';
$labels['today'] = 'dnes';
$labels['yesterday'] = 'včera';
$labels['geoip_license'] = 'Zde uvedené geografické údaje jsou založeny na databázích GeoLite2 Free vytvořené společností MaxMind, dostupných na <a href="http://www.maxmind.com">http://www.maxmind.com</a>.';
