<?php

$messages = array();
$messages['lastlogin_info'] = 'Letzte Anmeldung: $date von IP-Adresse $from $geo.';
$messages['noinfo'] = 'Keine Informationen vorhanden.';
$messages['timeout'] = 'Zeige letzte Sitzungsinformationen';

$labels = array();
$labels['lastlogin'] = 'Anmeldehistorie';
$labels['info'] = 'Informationen';
$labels['conf'] = 'Einstellungen';
$labels['fornseconds'] = 'für $n Sekunden';
$labels['recentactivity'] = 'Vergangene Anmeldungen:';
$labels['ip'] = 'IP-Adresse';
$labels['hostname'] = 'Name';
$labels['timestamp'] = 'Datum/Uhrzeit';
$labels['today'] = 'heute';
$labels['yesterday'] = 'gestern';
$labels['geoip_license'] = 'Die bereitgestellten Geodaten beruhen auf der freien, von MaxMind erstellten GeoLite2 Datenbank, abrufbar über <a href="http://www.maxmind.com">http://www.maxmind.com</a>.';
