<?php

$messages = array();
$messages['lastlogin_info'] = 'Last open session was on $date from IP address $from $geo.';
$messages['noinfo'] = 'No information available.';
$messages['timeout'] = 'Show last session information';

$labels = array();
$labels['lastlogin'] = 'Last login';
$labels['info'] = 'Information';
$labels['conf'] = 'Settings';
$labels['fornseconds'] = 'for $n seconds';
$labels['recentactivity'] = 'Recent activity:';
$labels['ip'] = 'IP address';
$labels['hostname'] = 'Name';
$labels['timestamp'] = 'Date/Time';
$labels['today'] = 'today';
$labels['yesterday'] = 'yesterday';
$labels['geoip_license'] = 'The geographic data provided here are based on GeoLite2 Free Databases created by MaxMind, available from <a href="http://www.maxmind.com">http://www.maxmind.com</a>.';
