<?php

$messages = array();
$messages['lastlogin'] = 'Ultimo acceso ha sido $date desde la IP $from $geo.';
$messages['noinfo']    = 'No hay informacion de acceso.';
$messages['timeout']   = 'Mostrar la informacin de acceso.';

$labels = array();
$labels['section_title'] = 'Ultimo acceso';
$labels['info'] = 'Informacion';
$labels['conf'] = 'Configurar';
$labels['fornseconds'] = 'por $n segundos';
$labels['recentactivity'] = 'Reciente Actividad:';
$labels['ip'] = 'IP address';
$labels['hostname'] = 'Nombre';
$labels['timestamp'] = 'Fecha/Hora';
$labels['today'] = 'hoy';
$labels['yesterday'] = 'ayer';
$labels['geoip_license'] = 'La geolocalizacion disponible esta basada en GeoLite2 Free Databases created by MaxMind, available from <a href="http://www.maxmind.com">http://www.maxmind.com</a>.';
