<?php

$messages = array();
$messages['lastlogin_info'] = 'Último acceso ha sido $date desde la IP $from $geo.';
$messages['noinfo'] = 'No hay información de acceso.';
$messages['timeout'] = 'Mostrar la información de acceso.';

$labels = array();
$labels['lastlogin'] = 'Último acceso';
$labels['info'] = 'Información';
$labels['conf'] = 'Configurar';
$labels['fornseconds'] = 'por $n segundos';
$labels['recentactivity'] = 'Reciente Actividad:';
$labels['ip'] = 'IP address';
$labels['hostname'] = 'Nombre';
$labels['timestamp'] = 'Fecha/Hora';
$labels['today'] = 'hoy';
$labels['yesterday'] = 'ayer';
$labels['geoip_license'] = 'La geolocalización disponible esta basada en GeoLite2 Free Databases creada por MaxMind, disponible en <a href="http://www.maxmind.com">http://www.maxmind.com</a>.';
