<?php

$messages['lastlogin_info'] = 'L\'ultima sessione è stata il $date dall\'indirizzo IP $from $geo. <a href="$more">[+]</a>';
$messages['noinfo'] = 'Nessuna informazione disponibile.';
$messages['timeout'] = 'Mostra le informazioni sull\'ultima sessione';

$labels['lastlogin'] = 'Ultimo accesso';
$labels['info'] = 'Informazioni';
$labels['conf'] = 'Impostazioni';
$labels['fornseconds'] = 'per $n secondi';
$labels['recentactivity'] = 'Attività recente:';
$labels['ip'] = 'Indirizzo IP';
$labels['hostname'] = 'Nome';
$labels['timestamp'] = 'Data/Ora';
$labels['today'] = 'oggi';
$labels['ieri'] = 'ieri';
$labels['geoip_license'] = 'I dati geografici forniti qui si basano sui database gratuiti GeoLite2 creati da MaxMind, disponibili su <a href="http://www.maxmind.com">http://www.maxmind. com</a>.';
$labels['ua'] = 'User Agent';
