<?php

$messages = array();
$messages['lastlogin_info'] = 'Laatste sessie was: $date van IP adres $from $geo.';
$messages['noinfo'] = 'Geen informatie beschikbaar.';
$messages['timeout'] = 'Bekijk de laatste sessie-informatie';

$labels = array();
$labels['lastlogin'] = 'Laatste login';
$labels['info'] = 'Informatie';
$labels['conf'] = 'Instellingen';
$labels['fornseconds'] = 'voor $n seconden';
$labels['recentactivity'] = 'Recente activiteit:';
$labels['ip'] = 'IP adres';
$labels['hostname'] = 'Naam';
$labels['timestamp'] = 'Datum/Tijd';
$labels['today'] = 'vandaag';
$labels['yesterday'] = 'gisteren';
$labels['geoip_license'] = 'De hier weergegeven geografische gegevens zijn gebaseerd op GeoLite2 Free Databases gemaakt door MaxMind, beschikbaar via <a href="http://www.maxmind.com"> http://www.maxmind.com </a>.';
