<?php

$messages = array();
$messages['lastlogin_info'] = 'A &uacute;ltima sessão aberta foi $date a partir do endereço IP $from $geo.';
$messages['noinfo'] = 'Sem informação disponível.';
$messages['timeout'] = 'Mostrar informação da última sessão';

$labels = array();
$labels['lastlogin'] = 'Último login';
$labels['info'] = 'Informação';
$labels['conf'] = 'Configuração';
$labels['fornseconds'] = 'durante $n segundos';
$labels['recentactivity'] = 'Actividade recente:';
$labels['ip'] = 'Endereço IP';
$labels['hostname'] = 'Nome';
$labels['timestamp'] = 'Data/Hora';
$labels['today'] = 'hoje';
$labels['yesterday'] = 'ontem';
$labels['geoip_license'] = 'Os dados geográficos mostrados são baseados nos dados <i>GeoLite2 Free Databases</i> criados pela MaxMind, disponíveis em <a href="http://www.maxmind.com">http://www.maxmind.com</a>. ';
