<?php

$messages = array();
$messages['lastlogin'] = 'Последний сессия была открыта $date с IP-адреса $from $geo.';
$messages['noinfo']    = 'Нет данных.';
$messages['timeout']   = 'Показывать информацию о последней сессии';

$labels = array();
$labels['section_title'] = 'Последний вход';
$labels['info'] = 'Информация';
$labels['conf'] = 'Настройки';
$labels['fornseconds'] = 'за $n секунд';
$labels['recentactivity'] = 'Недавняя активность:';
$labels['ip'] = 'IP адрес';
$labels['hostname'] = 'Имя';
$labels['timestamp'] = 'Дата/Время';
$labels['today'] = 'сегодня';
$labels['yesterday'] = 'вчера';
$labels['geoip_license'] = 'Географические данные, представленные здесь, основаны на бесплатных базах данных GeoLite2, созданных MaxMind, доступных на <a href="https://www.maxmind.com/ru/">https://www.maxmind.com/ru/</a>.';
