<?php

$messages = array();
$messages['lastlogin_info'] = 'Последняя сессия была открыта $date с IP-адреса $from $geo. <a href="$more">[+]</a>';
$messages['noinfo'] = 'Нет данных.';
$messages['timeout'] = 'Показывать информацию о последней сессии при входе';

$labels = array();
$labels['lastlogin'] = 'Последний вход';
$labels['info'] = 'Информация';
$labels['conf'] = 'Настройки';
$labels['fornseconds'] = 'в течении $n секунд';
$labels['recentactivity'] = 'Недавняя активность:';
$labels['ip'] = 'IP адрес';
$labels['hostname'] = 'Хост';
$labels['timestamp'] = 'Дата/Время';
$labels['today'] = 'сегодня';
$labels['yesterday'] = 'вчера';
$labels['geoip_license'] = 'Географические данные, представленные здесь, основаны на бесплатных базах данных GeoLite2, созданных MaxMind, доступных на <a href="https://www.maxmind.com/ru/">https://www.maxmind.com/ru/</a>.';
