<?php

$messages = array();
$messages['lastlogin_info'] = 'Din senaste session var $date via IP-adress $from $geo. <a href="$more">[+]</a>';
$messages['noinfo'] = 'Ingen information tillgänglig.';
$messages['timeout'] = 'Visa information från senaste sessionen';

$labels = array();
$labels['lastlogin'] = 'Tidigare inloggningar';
$labels['info'] = 'Information';
$labels['conf'] = 'Inställningar';
$labels['fornseconds'] = 'i $n sekunder';
$labels['recentactivity'] = 'Senaste aktivitet:';
$labels['ip'] = 'IP-adress';
$labels['hostname'] = 'Hostnamn';
$labels['timestamp'] = 'Datum/Tid';
$labels['today'] = 'i dag';
$labels['yesterday'] = 'I går';
$labels['geoip_license'] = 'The geographic data provided here are based on GeoLite2 Free Databases created by MaxMind <a href="http://www.maxmind.com">http://www.maxmind.com</a>.';
