<?php

$messages = array();
$messages['lastlogin_info'] = 'Остання сесія була відкрита на $date із IP-адреси  $from $geo.';
$messages['noinfo'] = 'Інформація відсутня.';
$messages['timeout'] = 'Показувати інформацію про останню сесію протягом';

$labels = array();
$labels['lastlogin'] = 'Last login';
$labels['info'] = 'Інформація';
$labels['conf'] = 'Налаштування';
$labels['fornseconds'] = ' $n секунд';
$labels['recentactivity'] = 'Поточна активність:';
$labels['ip'] = 'IP адреса';
$labels['hostname'] = 'Імя';
$labels['timestamp'] = 'Дата/Час';
$labels['today'] = 'сьогодні';
$labels['yesterday'] = 'вчора';
$labels['geoip_license'] = 'Географічні дані, представлені тут, засновані на безкоштовних базах даних GeoLite2, створених MaxMind, доступні із  <a href="http://www.maxmind.com">http://www.maxmind.com</a>.';
